# Generated by Django 4.2.5 on 2024-02-10 21:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("codeUyum", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                ("status", models.BooleanField(default=True)),
                ("barcode", models.CharField(blank=True, max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("tax", models.PositiveIntegerField(blank=True, default=20)),
                ("stockAmount", models.PositiveIntegerField(default=0)),
                ("photoPath", models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="chip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("codeUyum", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                ("status", models.BooleanField(default=True)),
                ("barcode", models.CharField(blank=True, max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("tax", models.PositiveIntegerField(blank=True, default=20)),
                ("stockAmount", models.PositiveIntegerField(default=0)),
                ("photoPath", models.CharField(blank=True, max_length=5)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chip_brands",
                        to="order.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chip_categories",
                        to="order.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="currencyRates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currencyUSD", models.CharField(default="USD", max_length=3)),
                (
                    "rateUSD",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=31.88, max_digits=10
                    ),
                ),
                ("currencyEUR", models.CharField(default="EUR", max_length=3)),
                (
                    "rateEUR",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=34.38, max_digits=10
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("codeUyum", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                ("status", models.BooleanField(default=True)),
                ("barcode", models.CharField(blank=True, max_length=50)),
                (
                    "priceBuying",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "priceSelling",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("tax", models.PositiveIntegerField(blank=True, default=20)),
                ("stockAmount", models.PositiveIntegerField(default=0)),
                ("photoPath", models.CharField(blank=True, max_length=5)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_brands",
                        to="order.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_categories",
                        to="order.category",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_currency",
                        to="order.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="empty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("codeUyum", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                ("status", models.BooleanField(default=True)),
                ("barcode", models.CharField(blank=True, max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("tax", models.PositiveIntegerField(blank=True, default=20)),
                ("stockAmount", models.PositiveIntegerField(default=0)),
                ("photoPath", models.CharField(blank=True, max_length=5)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empty_brands",
                        to="order.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empty_categories",
                        to="order.category",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empty_currency",
                        to="order.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="head",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("codeUyum", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                ("status", models.BooleanField(default=True)),
                ("barcode", models.CharField(blank=True, max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("tax", models.PositiveIntegerField(blank=True, default=20)),
                ("stockAmount", models.PositiveIntegerField(default=0)),
                ("photoPath", models.CharField(blank=True, max_length=5)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="head_brands",
                        to="order.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="head_categories",
                        to="order.category",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="head_currency",
                        to="order.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=15)),
                ("country", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="mainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mainCategory", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="powder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("codeUyum", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                ("status", models.BooleanField(default=True)),
                ("barcode", models.CharField(blank=True, max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("tax", models.PositiveIntegerField(blank=True, default=20)),
                ("stockAmount", models.PositiveIntegerField(default=0)),
                ("photoPath", models.CharField(blank=True, max_length=5)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powder_brands",
                        to="order.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powder_categories",
                        to="order.category",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powder_currency",
                        to="order.currency",
                    ),
                ),
                (
                    "mainCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powder_mainCategories",
                        to="order.maincategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unitProduct", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="waste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("codeUyum", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                ("status", models.BooleanField(default=True)),
                ("barcode", models.CharField(blank=True, max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("tax", models.PositiveIntegerField(blank=True, default=20)),
                ("stockAmount", models.PositiveIntegerField(default=0)),
                ("photoPath", models.CharField(blank=True, max_length=5)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_brands",
                        to="order.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_categories",
                        to="order.category",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_currency",
                        to="order.currency",
                    ),
                ),
                (
                    "mainCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_mainCategories",
                        to="order.maincategory",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_units",
                        to="order.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="toner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("codeUyum", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                (
                    "powderWeight",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "developerWeight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("status", models.BooleanField(default=True)),
                ("barcode", models.CharField(blank=True, max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("tax", models.PositiveIntegerField(blank=True, default=20)),
                ("stockAmount", models.PositiveIntegerField(default=0)),
                ("photoPath", models.CharField(blank=True, max_length=80)),
                (
                    "box",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toner_boxes",
                        to="order.box",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toner_brands",
                        to="order.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toner_categories",
                        to="order.category",
                    ),
                ),
                (
                    "chip",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toner_chips",
                        to="order.chip",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toner_currency",
                        to="order.currency",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toner_developers",
                        to="order.developer",
                    ),
                ),
                (
                    "empty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toner_empties",
                        to="order.empty",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toner_heads",
                        to="order.head",
                    ),
                ),
                (
                    "mainCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toner_mainCategories",
                        to="order.maincategory",
                    ),
                ),
                (
                    "powder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toner_powders",
                        to="order.powder",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toner_units",
                        to="order.unit",
                    ),
                ),
                (
                    "waste",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toner_wastes",
                        to="order.waste",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="taxOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taxOffice", models.CharField(max_length=15)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxOffice_location",
                        to="order.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sparepart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("codeUyum", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                ("status", models.BooleanField(default=True)),
                ("barcode", models.CharField(blank=True, max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("tax", models.PositiveIntegerField(blank=True, default=20)),
                ("stockAmount", models.PositiveIntegerField(default=0)),
                ("photoPath", models.CharField(blank=True, max_length=80)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sparepart_brands",
                        to="order.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sparepart_categories",
                        to="order.category",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sparepart_currency",
                        to="order.currency",
                    ),
                ),
                (
                    "mainCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sparepart_mainCategories",
                        to="order.maincategory",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sparepart_units",
                        to="order.unit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="powder",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="powder_units",
                to="order.unit",
            ),
        ),
        migrations.AddField(
            model_name="head",
            name="mainCategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="head_mainCategories",
                to="order.maincategory",
            ),
        ),
        migrations.AddField(
            model_name="head",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="head_units",
                to="order.unit",
            ),
        ),
        migrations.AddField(
            model_name="empty",
            name="mainCategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empty_mainCategories",
                to="order.maincategory",
            ),
        ),
        migrations.AddField(
            model_name="empty",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empty_units",
                to="order.unit",
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="mainCategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="developer_mainCategories",
                to="order.maincategory",
            ),
        ),
        migrations.AddField(
            model_name="developer",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="developer_units",
                to="order.unit",
            ),
        ),
        migrations.CreateModel(
            name="customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_number", models.CharField(blank=True, max_length=50)),
                ("customerCode", models.CharField(max_length=50)),
                ("companyName", models.CharField(max_length=50)),
                ("name", models.CharField(blank=True, max_length=50)),
                ("middleName", models.CharField(blank=True, max_length=50)),
                ("surname", models.CharField(blank=True, max_length=50)),
                ("district", models.CharField(blank=True, max_length=50)),
                ("customerType", models.CharField(blank=True, max_length=50)),
                ("adresName", models.CharField(blank=True, max_length=50)),
                ("contactPerson", models.CharField(blank=True, max_length=50)),
                (
                    "country",
                    models.CharField(blank=True, default="Türkiye", max_length=50),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=11)),
                ("adress", models.CharField(blank=True, max_length=250)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_city",
                        to="order.location",
                    ),
                ),
                (
                    "taxOffice",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_taxOffice",
                        to="order.taxoffice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="copier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("codeUyum", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                ("status", models.BooleanField(default=True)),
                ("barcode", models.CharField(blank=True, max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("tax", models.PositiveIntegerField(blank=True, default=20)),
                ("stockAmount", models.PositiveIntegerField(default=0)),
                ("photoPath", models.CharField(blank=True, max_length=80)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copier_brands",
                        to="order.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copier_categories",
                        to="order.category",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copier_currency",
                        to="order.currency",
                    ),
                ),
                (
                    "mainCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copier_mainCategories",
                        to="order.maincategory",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copier_units",
                        to="order.unit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chip",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chip_currency",
                to="order.currency",
            ),
        ),
        migrations.AddField(
            model_name="chip",
            name="mainCategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chip_mainCategories",
                to="order.maincategory",
            ),
        ),
        migrations.AddField(
            model_name="chip",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chip_units",
                to="order.unit",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_brands",
                to="order.brand",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_categories",
                to="order.category",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_currency",
                to="order.currency",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="mainCategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_mainCategories",
                to="order.maincategory",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_units",
                to="order.unit",
            ),
        ),
    ]
