# Generated by Django 4.2.5 on 2024-02-10 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toner",
            name="barcode",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="toner",
            name="box",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="toner_boxes",
                to="order.box",
            ),
        ),
        migrations.AlterField(
            model_name="toner",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="toner_brands",
                to="order.brand",
            ),
        ),
        migrations.AlterField(
            model_name="toner",
            name="chip",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="toner_chips",
                to="order.chip",
            ),
        ),
        migrations.AlterField(
            model_name="toner",
            name="developer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="toner_developers",
                to="order.developer",
            ),
        ),
        migrations.AlterField(
            model_name="toner",
            name="head",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="toner_heads",
                to="order.head",
            ),
        ),
        migrations.AlterField(
            model_name="toner",
            name="photoPath",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="toner",
            name="powderWeight",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="toner",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="toner",
            name="waste",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="toner_wastes",
                to="order.waste",
            ),
        ),
    ]
