# Generated by Django 4.2.5 on 2024-02-21 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_rename_developer_product_remove_chip_brand_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="currencyRates",
            new_name="currencyRate",
        ),
    ]
