# Generated by Django 4.2.5 on 2024-02-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_rename_currencyrates_currencyrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="rateEUR",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=34.9, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="taxOffice",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name="taxOffice",
        ),
    ]
