# Generated by Django 4.2.5 on 2024-03-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_remove_customer_adresname_alter_currencyrate_rateeur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="rateEUR",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=35.86, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="rateUSD",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=32.91, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
