# Generated by Django 4.2.5 on 2024-04-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_product_priceselling2_product_priceselling3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="district",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="rateEUR",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=35.73, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="rateUSD",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=33.25, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_dist",
                to="order.location",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand_name",
                to="order.brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories_name",
                to="order.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currency_name",
                to="order.currency",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="mainCategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mainCategories_name",
                to="order.maincategory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="photoPath",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_name",
                to="order.unit",
            ),
        ),
        migrations.CreateModel(
            name="taxoffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vd", models.CharField(max_length=40)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_city_tax",
                        to="order.location",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="customer",
            name="taxOffice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taxoffice_customer",
                to="order.taxoffice",
            ),
        ),
    ]
