# Generated by Django 4.2.5 on 2024-04-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_location_district_alter_currencyrate_rateeur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="rateEUR",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=35.71, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="rateUSD",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=33.23, max_digits=10
            ),
        ),
    ]
