# Generated by Django 4.2.5 on 2024-04-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_alter_currencyrate_rateeur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="rateEUR",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=35.69, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="rateUSD",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=33.24, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="taxoffice",
            name="city",
            field=models.CharField(max_length=15),
        ),
    ]
