# Generated by Django 4.2.5 on 2024-05-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_alter_currencyrate_rateeur_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="invoiceNumber",
            new_name="order_number",
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="rateEUR",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=36.27, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="rateUSD",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=33.4, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_orders",
                to="order.customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_orders",
                to="order.product",
            ),
        ),
    ]
