# Generated by Django 4.2.5 on 2024-06-13 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0020_rename_tax_rate_orderitem_tax_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="Tax_rate",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax",
            field=models.ForeignKey(
                default=20,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_tax",
                to="order.product",
            ),
            preserve_default=False,
        ),
    ]
