# Generated by Django 4.2.5 on 2024-06-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0022_alter_orderitem_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="tax",
            field=models.PositiveIntegerField(),
        ),
    ]
