# Generated by Django 4.2.5 on 2024-06-13 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0023_alter_orderitem_tax"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="tax",
        ),
    ]
