# Generated by Django 4.2.5 on 2024-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0024_remove_orderitem_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="discount_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
