# Generated by Django 4.2.5 on 2024-06-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0026_alter_orderitem_discount_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="discount_rate",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
