# Generated by Django 4.2.5 on 2024-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0028_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="shipping_adress",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_city",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
