# Generated by Django 4.2.5 on 2024-06-16 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0029_customer_shipping_adress_customer_shipping_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="shipping_city",
        ),
    ]
