# Generated by Django 4.2.5 on 2024-06-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0030_remove_customer_shipping_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_billed",
            field=models.BooleanField(default=False),
        ),
    ]
