# Generated by Django 4.2.5 on 2024-06-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0031_order_is_billed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="E_invoice",
            field=models.BooleanField(default=True),
        ),
    ]
