# Generated by Django 4.2.5 on 2024-06-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0033_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total_discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
