# Generated by Django 4.2.5 on 2024-06-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0034_invoice_total_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="grand_total_EUR",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="grand_total_USD",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
