# Generated by Django 4.2.5 on 2024-06-19 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0038_cashregister_expenseitem_paymentreceipt_debit_credit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credit",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="debit",
            name="expense_item",
        ),
        migrations.RemoveField(
            model_name="paymentreceipt",
            name="cash_register",
        ),
        migrations.RemoveField(
            model_name="paymentreceipt",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="paymentreceipt",
            name="expense_item",
        ),
        migrations.RemoveField(
            model_name="paymentreceipt",
            name="user",
        ),
        migrations.DeleteModel(
            name="CashRegister",
        ),
        migrations.DeleteModel(
            name="Credit",
        ),
        migrations.DeleteModel(
            name="Debit",
        ),
        migrations.DeleteModel(
            name="ExpenseItem",
        ),
        migrations.DeleteModel(
            name="PaymentReceipt",
        ),
    ]
