# Generated by Django 4.2.5 on 2024-06-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0040_cashregister_expenseitem_paymentreceipt_debit_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentreceipt",
            name="transaction_type",
            field=models.CharField(
                choices=[("Tahsilat", "Tahsilat"), ("Tediye", "Tediye")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="BuyingInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("invoice_date", models.DateTimeField(auto_now_add=True)),
                ("billing_address", models.CharField(blank=True, max_length=250)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "total_discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "grand_total_USD",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "grand_total_EUR",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("status", models.CharField(default="Pending", max_length=50)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buying_invoice",
                        to="order.order",
                    ),
                ),
            ],
        ),
    ]
