# Generated by Django 4.2.5 on 2024-06-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0041_alter_paymentreceipt_transaction_type_buyinginvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreceipt",
            name="eur_amount",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="usd_amount",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
    ]
