# Generated by Django 4.2.5 on 2024-06-22 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0044_alter_paymentreceipt_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debit",
            name="expense_item",
        ),
        migrations.DeleteModel(
            name="Credit",
        ),
        migrations.DeleteModel(
            name="Debit",
        ),
    ]
