# Generated by Django 4.2.5 on 2024-06-25 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0046_alter_paymentreceipt_transaction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_orders",
                to="order.customer",
            ),
        ),
        migrations.AlterField(
            model_name="paymentreceipt",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="order.customer",
            ),
        ),
        migrations.AlterField(
            model_name="paymentreceipt",
            name="transaction_type",
            field=models.CharField(
                choices=[("Tahsilat", "Tahsilat"), ("Tediye", "Tediye")], max_length=10
            ),
        ),
    ]
