# Generated by Django 4.2.5 on 2024-07-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0051_invoice_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="final_product",
            field=models.BooleanField(default=False),
        ),
    ]
