# Generated by Django 4.2.5 on 2024-07-18 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0052_product_final_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="final_product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stockAmount",
        ),
    ]
