# Generated by Django 4.2.5 on 2024-07-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0054_place_transfer_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="final_product",
            field=models.BooleanField(default=True),
        ),
    ]
