# Generated by Django 4.2.5 on 2024-07-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0055_product_final_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "powder_gram",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "developer_gram",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_product",
                        to="order.product",
                    ),
                ),
                (
                    "cartridge_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartridge_head_product",
                        to="order.product",
                    ),
                ),
                (
                    "chip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chip_product",
                        to="order.product",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_product",
                        to="order.product",
                    ),
                ),
                (
                    "empty_cartridge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empty_cartridge_product",
                        to="order.product",
                    ),
                ),
                (
                    "powder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powder_product",
                        to="order.product",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produced_product",
                        to="order.product",
                    ),
                ),
                (
                    "waste_box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_box_product",
                        to="order.product",
                    ),
                ),
            ],
        ),
    ]
