# Generated by Django 4.2.5 on 2024-07-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0056_production"),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="box",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_product",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="cartridge_head",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartridge_head_product",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="chip",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chip_product",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="developer_product",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="developer_gram",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="empty_cartridge",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empty_cartridge_product",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="powder",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="powder_product",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="powder_gram",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="product",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produced_product",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="waste_box",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waste_box_product",
                to="order.product",
            ),
        ),
    ]
