# Generated by Django 4.2.5 on 2024-07-19 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0057_alter_production_box_alter_production_cartridge_head_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="production",
            name="date",
        ),
        migrations.AlterField(
            model_name="production",
            name="box",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="box_productions",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="cartridge_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cartridge_head_productions",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="chip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chip_productions",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="developer_productions",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="developer_gram",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="empty_cartridge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empty_cartridge_productions",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="powder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="powder_productions",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="powder_gram",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productions",
                to="order.product",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="waste_box",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waste_box_productions",
                to="order.product",
            ),
        ),
    ]
