# Generated by Django 5.0 on 2024-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0058_remove_production_date_alter_production_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='priceBuying',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
