# Generated by Django 4.2.5 on 2024-07-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0059_inventory_pricebuying"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplierCode", models.CharField(max_length=50)),
                ("companyName", models.CharField(max_length=50)),
                ("taxOffice", models.CharField(blank=True, max_length=50, null=True)),
                ("tax_number", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("adress", models.CharField(blank=True, max_length=250, null=True)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "contactPerson",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
