# Generated by Django 4.2.5 on 2024-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0061_remove_buyinginvoice_order_buyinginvoice_supplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyinginvoice",
            name="billing_address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
