# Generated by Django 5.0 on 2024-08-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0063_rename_grand_total_buyinginvoice_grand_total_tl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyinginvoice',
            old_name='total_amount',
            new_name='total_amount_tl',
        ),
    ]
