# Generated by Django 5.0 on 2024-08-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_rename_total_amount_buyinginvoice_total_amount_tl'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinginvoice',
            name='total_amount_EUR',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buyinginvoice',
            name='total_amount_USD',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
