# Generated by Django 5.0 on 2024-08-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0065_buyinginvoice_total_amount_eur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyinginvoice',
            name='status',
        ),
        migrations.AddField(
            model_name='buyingitem',
            name='finalized_currency_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
