# Generated by Django 5.0 on 2024-08-05 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0067_remove_buyingitem_finalized_currency_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.supplier'),
        ),
    ]
