# Generated by Django 5.0 on 2024-08-06 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0069_rename_balance_cashregister_balance_eur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinginvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.customer'),
        ),
    ]
