# Generated by Django 5.0 on 2024-08-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0070_buyinginvoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinginvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='order.supplier'),
        ),
    ]
