# Generated by Django 5.0 on 2024-08-07 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_alter_buyinginvoice_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='currency',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='currency_name_bank', to='order.currency'),
            preserve_default=False,
        ),
    ]
