# Generated by Django 5.0 on 2024-08-07 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0072_cashregister_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Out', 'Out'), ('In', 'In')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='order.cashregister')),
                ('expense_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.expenseitem')),
                ('target_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='order.cashregister')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
