# Generated by Django 5.0 on 2024-08-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0073_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
