# Generated by Django 4.2.5 on 2024-08-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0074_remove_product_pricebuying_buyingitem_tax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_tr",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
