# Generated by Django 5.0 on 2024-08-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0074_orderitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
