# Generated by Django 4.2.5 on 2024-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0075_category_category_tr"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="final_product",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
