# Generated by Django 4.2.5 on 2024-08-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0076_category_final_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="priceBuying",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
