# Use an official Python runtime as a parent image
FROM python:3
COPY .  /usr/src/app
WORKDIR /usr/src/app/Simetri

# Install Chrome
RUN apt-get update && apt-get install -y wget gnupg \
    && wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update && apt-get install -y google-chrome-stable

# Install ChromeDriver
RUN wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/128.0.6613.89/chromedriver_linux64.zip \
    && unzip /tmp/chromedriver.zip -d /usr/local/bin/ \
    && rm /tmp/chromedriver.zip

# Install Python dependencies
COPY ../requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application code
#COPY . .

# Expose port 8000 and run the Django app
EXPOSE 8000
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "Simetri.wsgi:application"]


