# Use an official Python runtime as a parent image
FROM python:3

# Install dependencies for Chrome and ChromeDriver
RUN apt-get update && apt-get install -y wget gnupg unzip \
    && wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update && apt-get install -y google-chrome-stable

# Install ChromeDriver
RUN wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/128.0.6613.89/chromedriver_linux64.zip \
    && unzip /tmp/chromedriver.zip -d /usr/local/bin/ \
    && rm /tmp/chromedriver.zip

# Set the working directory
WORKDIR /Simetri

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r ../requirements.txt

# Copy the rest of the application code
COPY . /app/

# Expose port 8000 and run the Django app with Gunicorn
EXPOSE 10000
CMD ["gunicorn", "--bind", "0.0.0.0:10000", "Simetri.wsgi:application"]
