version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:10000 Simetri.wsgi:application
    volumes:
      - .:/Simetri
    ports:
      - "10000:10000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
